### ISSUE TITLE
Minor review recommendations

### ISSUE THREAD

**Issue by samreid** [phetsims/fraction-comparison#37]
From #36 

The changes look great!  I have a few very minor recommendations as you proceed:

(1) some annotations look like this:

```js
    // @public {Property.<string>} one of start/dragging/compare
    this.stateProperty = new StringProperty( 'start' );
```

It should also be noted when the property is read-only, like so:

```js
// @public (read-only) {Property.<string>} one of start/dragging/compare
```

In this case, it means that stateProperty is never reassigned.

(2)
In this code:
```js
  // constant
  var VALID_REPRESENTATION_VALUES = [
    'horizontal-bar',
    'vertical-bar',
    'circle',
    'chocolate',
    'different-sized-circles' ];
```

// constant should be labeled //constants, even if there is only one of them for now.

**Comment by veillette** [comment]
Thanks. The annotations for the Property were corrected and constant is now pluralized. Closing

**Comment by samreid** [comment]
Thanks @veillette, looks good.  As a new policy for you and your team, I'd like to recommend the following:

When an issue is reported by a code reviewer, designer or quality assurance team member, after you and your team has addressed the issue, please comment about what was done and reassign back to the original reporter to review/test and close.

**Comment by veillette** [comment]
Thanks.  We will follow this procedure from this point on..
