### ISSUE TITLE
remove Tween preload?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fraction-comparison#40]
I don't see TWEEN used anywhere in fraction-comparison or its dependencies, but I see this preload in package.json:

```js
    "preload": [
      "../sherpa/lib/Tween-r12.js"
    ]
```

Can this preload be removed?

**Comment by jonathanolson** [comment]
Assigning to responsible-dev.

**Comment by samreid** [comment]
I confirmed the sim uses twixt and that a debugger in the TWEEN constructor is not called.

**Comment by samreid** [comment]
Removed and tested, closing.
